service: gotcha
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2

plugins:
  - serverless-webpack

package:
  individually: true
  excludeDevDependencies: false

custom:
  webpack:
    includeModules: true

functions:
  inbound-websockets:
    handler: src/functions/inbound-websockets/index.handler
