service: gotcha
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: false

custom:
  webpack:
    includeModules: true

functions:
  api:
    handler: handler.api
    events:
      - http:
          path: /{proxy+}
          method: ANY
